// Code generated by go-bindata. (@generated) DO NOT EDIT.

// Package templates generated by go-bindata.
// sources:
// scripts/health-monitor.tpl.sh
// scripts/init.tpl.sh
package templates

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

// Name return file name
func (fi bindataFileInfo) Name() string {
	return fi.name
}

// Size return file size
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}

// Mode return file mode
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}

// ModTime return file modify time
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}

// IsDir return file whether a directory
func (fi bindataFileInfo) IsDir() bool {
	return fi.mode&os.ModeDir != 0
}

// Sys return file is sys mode
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _scriptsHealthMonitorTplSh = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x6c\x90\x41\x4b\xf3\x40\x10\x86\xef\xf3\x2b\xde\xf6\xfb\xae\x92\x16\xc1\x4b\xd1\x4b\xdb\x9b\xa8\x90\xa3\x48\xd9\x66\x27\xee\xe0\x76\x26\x64\x27\x7a\x10\xff\xbb\x34\xb6\x90\x42\xf7\x36\xf3\xb0\xbc\xcf\xbc\xff\x66\xd5\x5e\xb4\xda\x87\x92\xa8\xb0\xe3\xc6\xa0\x36\x68\x61\x3f\x8f\x9d\x74\xdc\x06\xc9\x44\xed\xa0\x8d\x8b\x29\x1a\x53\x0f\xa2\xdc\xc7\xdd\xc1\x54\xdc\x7a\xd1\x77\x7c\x13\xc0\x4d\x32\xcc\xd7\x67\xbe\xc1\x89\x23\x85\x82\xe2\xa1\x77\x8e\x98\xcd\x09\xf8\x4a\x92\x19\xaf\x58\xe2\x6d\x85\x68\x04\x00\xd2\x62\x06\x97\x03\xdb\xe0\xb8\x5b\xa0\xf1\x1e\x0d\xb2\x14\xc7\x03\xaa\xc8\x9f\x95\x0e\x39\xaf\xe0\x89\x75\xfc\x70\x25\x30\x06\x3e\x98\xe2\x68\xcc\x71\x4c\x3a\xbe\xee\x43\x72\x9e\x78\x9f\xd6\x25\x33\x77\xb8\x5d\x8c\x23\xe7\xc2\x17\xfb\xff\xf5\xe3\x76\xfb\xb2\xab\xb7\xeb\xe7\xa7\x4d\x3d\xa2\x56\x08\x88\xa6\x4c\x3f\x44\x17\xf8\x7e\xb9\xa0\x3f\x99\xfa\x78\x26\x12\x87\xec\x09\x93\x7e\x5a\xeb\x27\x06\x73\xba\xda\x22\xfd\x06\x00\x00\xff\xff\x00\x11\x69\x9f\x91\x01\x00\x00")

func scriptsHealthMonitorTplShBytes() ([]byte, error) {
	return bindataRead(
		_scriptsHealthMonitorTplSh,
		"scripts/health-monitor.tpl.sh",
	)
}

func scriptsHealthMonitorTplSh() (*asset, error) {
	bytes, err := scriptsHealthMonitorTplShBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "scripts/health-monitor.tpl.sh", size: 401, mode: os.FileMode(420), modTime: time.Unix(1, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _scriptsInitTplSh = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x64\x51\x5d\x6b\xdb\x40\x10\x7c\xdf\x5f\x31\xb9\x08\xdc\x06\x64\x15\xfa\xd6\x46\x81\xb6\xc8\xd4\x50\x92\x40\x4b\x5f\x1c\x57\x9c\x75\x2b\xfb\x5a\xdd\xc9\xdc\x9d\x4d\x43\x94\xff\x5e\x74\xf2\x77\x5f\xb4\xda\xd5\x68\x66\x76\xe7\xfa\x2a\x5b\x68\x9b\x2d\xa4\x5f\x11\x4d\xa6\xdf\x8a\x3c\xe3\x50\x65\x55\x6b\x83\xd4\x96\x9d\xea\x5f\x6b\xbd\x1c\x87\xd6\x34\xe4\x0c\x92\x1e\x44\xba\xc6\x0c\x57\x48\x6b\x88\x38\x10\x98\x7f\x44\x58\xb1\x25\xc0\xfc\x51\xda\x21\x5d\xe3\x82\x89\x00\xae\x56\x2d\x46\xda\xac\x5b\x17\x3c\x72\xcc\xc4\xa5\x9a\xdb\xd8\xa0\x0d\x97\x37\x51\x50\xcc\x47\xb8\xdb\x4b\x10\x70\x04\x62\xb0\x05\xc5\xb5\xdc\x34\x01\x77\x47\x58\xad\x89\xae\xb1\xf1\x0c\x6d\x7f\x73\x15\x58\x41\x1b\xb9\x64\x48\x0f\x2f\xad\x5a\xb4\x7f\x87\x01\xed\xba\x32\x76\x65\xa3\x2d\xe7\x22\x79\xb3\x74\xbc\xc6\xd9\xa7\x61\x69\x74\xf0\xac\x90\x32\x46\x3e\xfb\x35\xc3\xfc\x26\xcb\x46\x6f\x05\xad\xe5\xc6\xf3\x00\xcc\x5f\x5e\x30\x8e\xfd\x97\xbd\xd3\x69\x24\x78\x7d\xa5\xf8\xaf\x06\x84\xef\x92\xff\x85\xbb\x73\xc1\x1c\x4f\x22\x39\x21\x7e\x12\xdd\x52\xec\x6e\x4f\x9f\xa7\xf7\xe5\xe3\xa7\x1f\x5f\xa3\xda\x42\x5b\xe9\x9e\x1f\x65\x58\xf5\x22\x87\xdb\x27\x7b\x10\x51\x71\xff\xb3\x3c\x26\xeb\x9f\x7d\x60\xa3\x76\xf5\xe4\xf4\x63\xcf\x6e\xab\x2b\x1e\xab\xec\xfd\xbb\x94\xed\xb6\xdc\x25\xdf\x97\xb3\xc0\xf7\x84\xa7\xa1\x57\x32\xe0\xf6\xb6\x78\x98\xa0\x43\x60\xc6\x01\x44\xb3\xef\x03\xef\x9c\x0a\xbb\xd5\xae\xb5\x86\x6d\xc8\x45\x5c\xe0\xe0\xf2\x43\xd2\x3f\x05\x15\x0f\x13\x02\x06\x6f\x55\x68\xa0\x24\x9b\xd6\xa6\x8e\x9b\x56\xaa\x3e\xd9\x7f\x01\x00\x00\xff\xff\x7c\x1c\xd5\x51\xb0\x02\x00\x00")

func scriptsInitTplShBytes() ([]byte, error) {
	return bindataRead(
		_scriptsInitTplSh,
		"scripts/init.tpl.sh",
	)
}

func scriptsInitTplSh() (*asset, error) {
	bytes, err := scriptsInitTplShBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "scripts/init.tpl.sh", size: 688, mode: os.FileMode(420), modTime: time.Unix(1, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"scripts/health-monitor.tpl.sh": scriptsHealthMonitorTplSh,
	"scripts/init.tpl.sh":           scriptsInitTplSh,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("nonexistent") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"scripts": &bintree{nil, map[string]*bintree{
		"health-monitor.tpl.sh": &bintree{scriptsHealthMonitorTplSh, map[string]*bintree{}},
		"init.tpl.sh":           &bintree{scriptsInitTplSh, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
